version: 0.2

env:
  variables:
    BUCKET_NAME: "codepipeline-sample-nodejs.bucket"
  exported-variables:
    - BUCKET_NAME

phases:
  build:
    on-failure: ABORT
    commands:
      - echo Build starting on ${date}
      - echo compressing src directory
      - zip -r src.zip src
artifacts:
  files:
    - '**/*'
  base-directory: 'src'
  discard-paths: no
  name: pm2-sample
